# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{

  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  #  boot.extraModulePackages = with config.boot.kernelPackages; [ zenpower ];
  #  boot.blacklistedKernelModules = [ "k10temp" ];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/adc31b8b-a138-4156-8069-f7600c9f0e4c";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8FE5-03D0";
    fsType = "vfat";
  };

  swapDevices = [{ label = "swap"; }];
  hardware.opengl = {
    driSupport = true;
    driSupport32Bit = true;
    enable = true;
    extraPackages = with pkgs; [
      rocmPackages_5.clr.icd
      rocmPackages_5.clr
      rocmPackages_5.rocminfo
      rocmPackages_5.rocm-runtime
    ];
  };
  systemd.tmpfiles.rules =
    [ "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages_5.clr}" ];
  environment.variables = {
    # As of ROCm 4.5, AMD has disabled OpenCL on Polaris based cards. So this is needed if you have a 500 series card. 
    ROC_ENABLE_PRE_VEGA = "1";
  };
  hardware.bluetooth = {
    enable = true;
    package = pkgs.bluez;
    settings = {
      General = { Experimental = "330859bc-7506-492d-9370-9a6f0614037f"; };
    };
  };
  hardware.firmware = [ pkgs.linux-firmware ];
  hardware.enableAllFirmware = true;
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
